language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3.3-5.2-alpha1
install:
    - pip install -U pip setuptools # need updated pip for caching
    - pip install .[test]
script:
    - python -m zope.lifecycleevent.tests
notifications:
    email: false

cache: pip
