language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy-5.6.0
  - pypy3.3-5.5-alpha
script:
  - coverage run -m zope.testrunner --test-path=src

after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
